apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-nolocfast'
spec:
  ttlSecondsAfterFinished: 60
  completions: 8
  parallelism: 8
  completionMode: Indexed
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 6
            memory: 256Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/uberlapse:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            sudo mkdir -p /home/docker/.cache/torch/hub/checkpoints/
            sudo chown docker /home/docker/.cache/torch/hub/checkpoints/ -R
            cp checkpoints/vgg16-397923af.pth /home/docker/.cache/torch/hub/checkpoints/vgg16-397923af.pth
            SCENES=(ours/uw1 ours/uw2 ours/pg ours/hike_07_08_gopro_4 ours/hike_09_26_7 ours/hike_1008_2 ours/hike_09_26_1 advanced/Ballroom intermediate/M60 intermediate/Panther intermediate/Playground intermediate/Train advanced/Auditorium advanced/Courtroom advanced/Museum train/Barn train/Caterpillar train/Church train/Courthouse train/Ignatius train/Meetingroom train/Truck)
            SKIPS=(0 0 0 2 0 2 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4)
            FOVS=(85 73 69 92 69 69 69 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            SCENE_NAME=${SCENE}/skip_${SKIP}
            python localTensoRF/train.py --config localTensoRF/configs/uberlapse.txt \
            --datadir ${SCENE_NAME} --multiGPU 0 \
            --fov ${FOVS[$JOB_COMPLETION_INDEX]} \
            --expname nolocfast \
            --render_only 0 \
            --optimize_focal 1 \
            --n_init_frames 5 \
            --with_GT_poses 0 \
            --optimize_poses 1 \
            --lr_poses_init 3e-4 \
            --opasity_gamma 1 \
            --loss_depth_weight_inital 1e-1 \
            --loss_flow_weight_inital 1e1 \
            --L1_weight_inital 1e-4 \
            --subsequence 0 -1 \
            --resize_h -1 \
            --n_iters 20000 \
            --upsamp_list 1000 2000 3000 4000 6000 \
            --N_voxel_init 262144 \
            --N_voxel_final 262144000 \
            --n_overlap 30 \
            --new_rf_init 0 \
            --shadingMode MLP_Fea_late_view \
            --fea_pe 3 \
            --patch_d_tv_weight 0 \
            --patch_batch_size 0 \
            --patch_size 16 \
            --distortion_loss_weight 0.0 \
            --fea2denseAct softplus \
            --add_frame_reset_rf_opt 1 \
            --density_shift -5 \
            --TV_weight_density 0 \
            --TV_weight_app 0 \
            --batch_size 4096 \
            --add_frames_every 200 \
            --max_drift 50000000 \
            --n_max_frames 10000 \
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
