apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-colmapngp'
spec:
  ttlSecondsAfterFinished: 60
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 4
            memory: 16Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/uberlapse:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(photoreal/couch photoreal/climbing_frame photoreal/fox)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            sudo chown docker data/sequenced/${SCENE} -R
            sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
            mkdir data/sequenced/${SCENE}/text
            colmap model_converter --input_path data/sequenced/${SCENE}/sparse/0 --output_path data/sequenced/${SCENE}/text --output_type TXT
            python colmap2nerf.py --images data/sequenced/${SCENE}/images --aabb_scale 1 --colmap_db data/sequenced/${SCENE}/database.db --text  data/sequenced/${SCENE}/text --out data/sequenced/${SCENE}/transforms.json
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
