apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-colmapmulti'
spec:
  ttlSecondsAfterFinished: 60
  completions: 15
  parallelism: 15
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 16
            memory: 56Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/uberlapse:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(ours/uw1 ours/uw2  ours/uw3 ours/uw4 ours/lake22_1 ours/lake22_2 ours/lake22_3  ours/lake22_4 ours/pg ours/hike_07_08_gopro_4 ours/hike_09_26_7 ours/hike_1008_4 ours/hike_1008_6 ours/hike_1008_2 ours/hike_09_26_1)
            SKIPS=(0 0 0 0 0 0 0 2 0 2 0 3 3 2 0)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            sudo chown docker data/sequenced/${SCENE}/skip_${SKIP} -R
            sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
            bash comparison/multinerf/scripts/local_colmap_and_resize.sh data/sequenced/${SCENE}/skip_${SKIP}
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
