apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-render-mipnerf3604'
spec:
  ttlSecondsAfterFinished: 60
  completions: 7
  parallelism: 7
  completionMode: Indexed
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 4
            memory: 96Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/mipnerf:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(ours/uw1 ours/uw2 ours/pg ours/hike_07_08_gopro_4 ours/hike_09_26_7 ours/hike_1008_2 ours/hike_09_26_1 intermediate/M60 intermediate/Panther intermediate/Playground intermediate/Train advanced/Auditorium advanced/Ballroom advanced/Courtroom advanced/Museum train/Barn train/Caterpillar train/Church train/Courthouse train/Ignatius train/Meetingroom train/Truck)
            SKIPS=(0 0 0 2 0 2 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            SCENE_NAME=${SCENE}/skip_${SKIP}
            cd comparison/multinerf
            export XLA_PYTHON_CLIENT_MEM_FRACTION=0.87; python -m render --gin_configs=configs/360.gin --gin_bindings="Config.data_dir = '../../data/sequenced/${SCENE_NAME}'" --gin_bindings="Config.checkpoint_dir = '../../data/logs_eval/mipnerf360/${SCENE_NAME}/checkpoints'" --gin_bindings="Config.render_dir = '../../data/logs_eval/mipnerf360/${SCENE_NAME}/render_smooth4'" --gin_bindings="Config.render_path = True" --logtostderr
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
