apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-train-scnerf-colmap'
spec:
  ttlSecondsAfterFinished: 60
  completions: 15
  parallelism: 15
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 16
            memory: 96Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/uberlapse:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(intermediate/M60 intermediate/Panther intermediate/Playground intermediate/Train advanced/Auditorium advanced/Ballroom advanced/Courtroom advanced/Museum train/Barn train/Caterpillar train/Church train/Courthouse train/Ignatius train/Meetingroom train/Truck)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIPS=(4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 3)
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            SCENE_NAME=${SCENE}/skip_${SKIP}
            sudo mkdir -p /home/docker/.cache/torch/hub/checkpoints/
            sudo chown docker /home/docker/.cache/torch/hub/checkpoints/ -R
            cp checkpoints/vgg16-397923af.pth /home/docker/.cache/torch/hub/checkpoints/vgg16-397923af.pth
            cp checkpoints/vgg.pth /home/docker/.cache/torch/hub/checkpoints/vgg.pth
            cd comparison/SCNeRF/nerfplusplus
            python ddp_train_nerf.py --config configs/tanks_and_temples/tat_intermediate_M60_ours.txt --basedir ../../../data/logs_eval/scnerf_colmap --datadir ../../../data/sequenced/ --scene ${SCENE_NAME} --expname ${SCENE_NAME}
            python ddp_test_nerf.py --config configs/tanks_and_temples/tat_intermediate_M60_ours.txt --render_splits test --basedir ../../../data/logs_eval/scnerf_colmap --datadir ../../../data/sequenced/ --scene ${SCENE_NAME} --expname ${SCENE_NAME}
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
