apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-train-nerfmm-colmap'
spec:
  ttlSecondsAfterFinished: 60
  completions: 15
  parallelism: 15
  completionMode: Indexed
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 6
            memory: 64Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/uberlapse:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(intermediate/M60 intermediate/Panther intermediate/Playground intermediate/Train advanced/Auditorium advanced/Ballroom advanced/Courtroom advanced/Museum train/Barn train/Caterpillar train/Church train/Courthouse train/Ignatius train/Meetingroom train/Truck)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIPS=(4 4 4 4 4 4 4 4 4 4 4 4 4 4 4)
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            SCENE_NAME=${SCENE}/skip_${SKIP}
            sudo mkdir -p /home/docker/.cache/torch/hub/checkpoints/
            sudo chown docker /home/docker/.cache/torch/hub/checkpoints/ -R
            cp checkpoints/vgg16-397923af.pth /home/docker/.cache/torch/hub/checkpoints/vgg16-397923af.pth
            cp checkpoints/vgg.pth /home/docker/.cache/torch/hub/checkpoints/vgg.pth
            cd comparison/nerfmm
            python tasks/nerfmm/train.py --base_dir='../../data/sequenced' --scene_name=${SCENE_NAME} --use_ndc=False --resize_ratio=1
            python tasks/nerfmm/eval.py --ckpt_dir=../../data/logs_eval/nerfmm_colmap --base_dir=../../data/sequenced --scene_name=${SCENE_NAME} --use_ndc=False --resize_ratio=1
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
