apiVersion: batch/v1
kind: Job
metadata:
  name: 'uberlapse-testnmerge-meganerf'
spec:
  ttlSecondsAfterFinished: 60
  completions: 7
  parallelism: 7
  completionMode: Indexed
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: uberlapse
        resources:
          limits:
            cpu: 4
            memory: 96Gi
            nvidia.com/gpu: 1
        image: "dtr.thefacebook.com/ameuleman/meganerf:latest"
        volumeMounts:
        - name: uberlapse
          mountPath: /mnt/uberlapse
        command:
          - "bash"
          - "-c"
          - |
            cd /mnt/uberlapse/ameuleman
            SCENES=(train/Barn train/Caterpillar train/Church train/Courthouse train/Ignatius train/Meetingroom train/Truck intermediate/M60 intermediate/Panther intermediate/Playground intermediate/Train advanced/Auditorium advanced/Ballroom advanced/Courtroom advanced/Museum)
            SKIPS=(4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4)
            SCENE=${SCENES[$JOB_COMPLETION_INDEX]}
            SKIP=${SKIPS[$JOB_COMPLETION_INDEX]}
            SCENE_NAME=${SCENE}/skip_${SKIP}
            cd comparison/mega-nerf
            python scripts/merge_submodules.py --config_file configs/mega-nerf/quad.yaml --ckpt_prefix ../../data/logs_eval/meganerf/${SCENE_NAME}/exp- --centroid_path ../../data/logs_eval/meganerf/${SCENE_NAME}/masks/params.pt --output ../../data/logs_eval/meganerf/${SCENE_NAME}/results \
            --train_iterations 250000
            python mega_nerf/eval.py --config_file configs/mega-nerf/quad.yaml --exp_name ../../data/logs_eval/meganerf/${SCENE_NAME}/exp- --dataset_path ../../data/logs_eval/meganerf/${SCENE_NAME}  --container_path ../../data/logs_eval/meganerf/${SCENE_NAME}/results
      volumes:
      - name: uberlapse
        persistentVolumeClaim:
          claimName: uberlapse
      priorityClassName: high
